version: "3"

services:
  db:
    image: tobi312/rpi-postgresql
    ports:
      - 5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-gogs}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-gogs}
      - POSTGRES_DB=${POSTGRES_DB:-gogs}

    networks:
      - gogs-network
 
  gogs:
    image: gogs/gogs-rpi
    restart: always
    networks:
      - gogs-network
    volumes:
      - /var/gogs:/data
    ports:
      - "3000:3000"
      - "10022:22"
 
networks:
  gogs-network:

volumes:
  gogs:
    driver: local

