version: "3"

services:
  db:
    image: tobi312/rpi-postgresql
    ports:
      - 5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-gitea}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-gitea}
      - POSTGRES_DB=${POSTGRES_DB:-gitea}

    networks:
      - gitea-network
 
  gitea:
    build:
      context: .
      dockerfile: Dockerfile.rpi
    restart: always
    networks:
      - gitea
    volumes:
      - gitea:/data
    ports:
      - "3000:3000"
      - "2222:22"
    depends_on:
      - db

networks:
  gitea-network:

volumes:
  gitea:
    driver: local

