version: '3'
services:
  db:
    image: tobi312/rpi-postgresql
    ports:
      - 5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-gogs}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-gogs}
      - POSTGRES_DB=${POSTGRES_DB:-gogs}

    networks:
      - gogs-network
 
  gogs:
    restart: unless-stopped
    image: gogs/gogs-rpi
    volumes:
      - /var/gogs:/data
    ports:
      - "10022:22"
      - "3000:3000"
    networks:
      - gogs-network
    depends_on:
      - db

networks:
  gogs-network:
